version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quizflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quizflow
      MYSQL_USER: quizflow_user
      MYSQL_PASSWORD: quizflow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:7.2-alpine
    container_name: quizflow-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mq:
    image: rabbitmq:3.13-management-alpine
    container_name: quizflow-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613" # Cổng STOMP phục vụ tính năng Chat/WebSocket
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: quizflow-meilisearch
    restart: always
    environment:
      - MEILI_MASTER_KEY=masterKey123
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

  backend:
    build:
      context: ./Backend/quizflow
      dockerfile: Dockerfile
    container_name: quizflow-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - REDIS_HOST=cache
      - RABBITMQ_HOST=mq
    depends_on:
      - db
      - cache
      - mq

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: quizflow-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  meilisearch_data:
