version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: quizflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: quizflow
      MYSQL_USER: quizflow_user
      MYSQL_PASSWORD: quizflow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cache:
    image: redis:7.2-alpine
    container_name: quizflow-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mq:
    image: rabbitmq:3.13-management-alpine
    container_name: quizflow-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
