spring:
  application:
    name: quizflow
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:quizflow}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USER:quizflow_user}
    password: ${DB_PASSWORD:quizflow_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:5}
      idle-timeout: 300000 # 5 phút
      max-lifetime: 600000 # 10 phút
      connection-timeout: 20000 # 20 giây
      leak-detection-threshold: 5000 # 5 giây phát hiện rò rỉ kết nối

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000 # Ép Java văng lỗi sau 2 giây nếu không kết nối được thay vì chờ vô tận

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false # CỰC KỲ QUAN TRỌNG: Thất bại thì KHÔNG lặp lại vô tận, mà ném vào DLQ
        retry:
          enabled: true # Bật tính năng tự động thử lại
          initial-interval: 1000 # Đợi 1s ở lần thử đầu tiên
          max-retries: 3 # Thử tối đa 3 lần
          multiplier: 2.0 # Thời gian đợi gấp đôi sau mỗi lần thử (1s -> 2s -> 4s)

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:vdtprojectsecretkeyquizflow12345}
  iv: ${ENCRYPTION_IV:quizflowdefaulti}

jwt:
  secret: ${JWT_SECRET:quizflowjwtsecretkey2026hustuniversity}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

cloudinary:
  cloud-name: avgccvua
  api-key: 798122979194662
  api-secret: hImbOTtMacwUsD71ussbxO0vxyc
